### ISSUE TITLE
refresh materialized views

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/NetworkDashboards#147]
When i loaded new data the graphs were not updated and it had to do a manual refresh using

REFRESH MATERIALIZED VIEW data_density 

Why is this needed, does these have to be added in a step you do when new data is uploaded maybe?

**Comment by aspedrosa** [comment]
All materialized views are updated automatically after an upload.
Some of them are not being updated because there are some materialized **queries** that don't have a materialized **view** associated, so when it tries to do the `REFRESH MATERIALIZED VIEW` command it fails and the rest of the materialized **views** are not updated.

Because some materialized **views** were using date fields that were converted to text and Postgres can't make that transformation automatically, I had to drop those materialized **views**.
I will remove the associated materialized **queries**.

However, we need to change the code so it ignores those errors and refreshes all the other materialized **views**.

**Comment by PRijnbeek** [comment]
Please do not drop views without saving the queries do not want to make them again from scratch that is a lot of work.

Why does your answer apply to the data_density is not clear to me.

**Comment by aspedrosa** [comment]
I already drop the missing materialized **views**. They are not being used on the new Per Database dashboard and are documented [here](https://ehden.github.io/NetworkDashboards/).

> Why does your answer apply to the data_density is not clear to me.

Imagine we have the following materialized **QUERIES**: a, b and c.
b doesn't have a materialized **VIEW** on Postgres.
To refresh all materialized **VIEWS** we do a for on all materialized **QUERIES** and run `REFRESH MATERIALIZED VIEW {name}`.
a is refreshed. b will raise the exception `relation "b" does not exist`, leading to the asynchronous task to stop and c is not refreshed.

**Comment by PRijnbeek** [comment]
Sorry still not clear. I just uploaded new IPCI data and de data density plot is not updated automatically. When i manually run the REFRESH MATERIALIZED VIEW it is.

**Comment by aspedrosa** [comment]
How much time did you wait? Refreshes took about 2 min.

**Comment by PRijnbeek** [comment]
Okay so it might be waiting longer.. thanks, re-open the issue if needed.

**Comment by PRijnbeek** [comment]
re-opening this issue. A new data source uploaded that but it seem the views are not updated (waited one hour).

![image](https://user-images.githubusercontent.com/7252105/103798741-6b201a00-504a-11eb-931e-3bebb19d7960.png)]

You can see all the tables and figures that not got updated if you look at that dashboard

MDH.

**Comment by PRijnbeek** [comment]
see above

**Comment by PRijnbeek** [comment]
After manually running the refresh I get this:

![image](https://user-images.githubusercontent.com/7252105/103800348-97d53100-504c-11eb-9d37-5215a034ad46.png)

**Comment by PRijnbeek** [comment]
Also confirmed with this one REFRESH MATERIALIZED VIEW public.visit_type_table 

please check this for the other that now say no_results

**Comment by joaorafaelalmeida** [comment]
There was an issue during the refresh of the materialized views after one upload. If one fails due to a wrong query, for instance, the remaining will not be refreshed. Now, this is solved, and it was tested with the SIDIAP database.
