### ISSUE TITLE
List of used Analysis Id Achilles

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/NetworkDashboards#29]
Can you tell me which Analysis Ids from Achilles are used in the Dashboard? Maybe we should add a csv file in the repository and refer to this in the Readme to explain which are used for transparancy. The new export function can then be restricted to these ids in Achilles R.

**Comment by joaorafaelalmeida** [comment]
Hi Peter,
After the TC that we had last Friday and seeing this issue, we built a python tool intending to simplify the data extraction and filtering. If you want, you can check it at https://github.com/bioinformatics-ua/AchillesLite
However, answering your question, the current analysis ids used are the following (I need to double-check this because there are 2 queries that I need to discuss with Maxim):
108, 1, 101, 3, 2, 110, 111, 112, 201, 501, 502, 405, 604, 705, 805, 1805, 2105, 401, 601, 701, 801, 1801, 2101, 2201.

The idea of this tool was to separate things from the Achilles tool.

**Comment by PRijnbeek** [comment]
Hi,

                I do think this is making it quite complex to run actually. It requires docker, people to run python commands etc  to do some simple queries on the database.
                Will this work against any of the supported DBMs?

                It is a few lines of code to add this in Achilles R which they have to run anyway when they update their Atlas.

                So I am not sure this will be used much once Anthony added the function to export to csv?

                p.s. do you have skype?

                Peter

**Comment by joaorafaelalmeida** [comment]
The updated list of analysis_ids is:
108, 1, 101, 3, 2, 110, 111, 112, 201, 501, 502, 405, 604, 705, 805, 1805, 2105, 401, 601, 701, 801, 1801, 2101, 2201,  200, 400, 600, 700, 800, 1800, 109, 506
